<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <style>
            * {
    font-size: 14px;
    font-family: 'Times New Roman';
}

td,
th,
tr,
table {
    border-top: 1px solid black;
    border-collapse: collapse;
}

td.description,
th.description {
    width: 120px;
    max-width: 120px;
    text-align: center;
}

td.quantity,
th.quantity {
    width: 90px;
    max-width: 90px;
    word-break: break-all;
    text-align: center;
}

td.price,
th.price {
    width: 90px;
    max-width: 90px;
    word-break: break-all;
    text-align: center;
}

.centered {
    text-align: center;
    align-content: center;
}

.ticket {
    width: 325px;
    max-width: 325px;
}

img {
    max-width: inherit;
    width: inherit;
}

@media print {
    .hidden-print,
    .hidden-print * {
        display: none !important;
    }
}
        </style>
        <title>Receipt</title>
    </head>
    <body>
        <?php
	include 'connect.php';
        $web = "select *from manage_website where id = '1'";
    $res_web = $conn->query($web);
    $website = mysqli_fetch_array($res_web);
    $que="SELECT * FROM `drinks_invoice` WHERE id='".$_GET["id"]."'";
    $query=$conn->query($que);
    $drink=mysqli_fetch_assoc($query);
        ?>
        <div class="ticket">
            <center><img src="uploadImage/Logo/<?php echo $website['logo'];?>" alt="Logo" style="width:230px;"></center>
           <strong>
               <center> 
           <?php echo '<h3 style="font-size: 25px;line-height: 0px;">'.$website['hotel_name'].'</h3>'; ?>
           </center>
           <p class="centered">
                <?php echo '<b>Email :</b> '.$website['email'].'<br>
    <b>Phone No :</b> '.$website['phone_no'].'<br>
    <b>Address :</b> '.$website['address'].' '.$website['city'].' '.$website['zip_code'].''; ?>
            </p>
           
            <?php echo '<p style="text-align: end;"><b>Date : </b> '.date('d M Y  h:ia').'</p>'; ?> <?php
date_default_timezone_set("Africa/Tunis");

?></strong>
            <hr>
            <p>
                <?php echo '<b>Customer Name :</b> '.$drink['cust_name'].'<br>
                <b>Address :</b> '.$drink['cust_address'].'<br>
    <b>Email :</b> '.$drink['cust_email'].'<br>
    <b>No :</b> '.$drink['cust_contact'].'<br>
    '; ?>
            </p>
            <table>
                <thead>
                    <tr>
                        <th class="quantity">Q.#</th>
                        <th class="description">Description</th>
                    
                        <th class="price">Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $sql_items = "select * from drinks_invoice_items where drinks_invoice_id = '".$drink['id']."'";
                        $res_items = $conn->query($sql_items);
                        $i=0;
                        while($item = mysqli_fetch_array($res_items)){
                            $sql = "select *from drinks where id = '".$item['drink_id']."'";
      $rep = $conn->query($sql);
      $product = mysqli_fetch_array($rep);
      $i++;
      echo '<tr><td class="quantity">'.$item['qty'].'</td><td class="description">'.$product['item_name'].'</td><td class="price">₵' .$item['price'].'</td></tr>';
     
    }
    echo '<tr><td class="quantity"></td>
                        <td class="description">Tax 18%</td><td class="price">₵' .$drink['total_amount']*0.18.'</td></tr>';
                        echo '<tr><td class="quantity"></td>
                        <td class="description">TOTAL</td><td class="price">₵' .$drink['total_amount']*0.18+$drink['total_amount'].'</td></tr>';   
                    ?>
                    <!--<tr>
                        <td class="quantity">1.00</td>
                        <td class="description">ARDUINO UNO R3</td>
                        <td class="price">$25.00</td>
                    </tr>
                    
                    <tr>
                        <td class="quantity"></td>
                        <td class="description">TOTAL</td>
                        <td class="price">$55.00</td>
                    </tr>-->
                </tbody>
            </table>
            <p>Invoice generated by : <?php echo $_SESSION['fname'].' '.$_SESSION['lname']; ?></p>
            <p class="centered"><strong>Thanks for your purchase!</strong>
                </p>
        </div>
        <button id="btnPrint" class="hidden-print">Print</button>
        <script>
            const $btnPrint = document.querySelector("#btnPrint");
$btnPrint.addEventListener("click", () => {
    window.print();
});
        </script>
    </body>
</html>